apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-app
  name: nodejs-app
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: nodejs-app
