---
#Secret
apiVersion: v1
data:
  MONGODB_URI: bW9uZ29kYjovL2FkbWludXNlcjpwYXNzd29yZDEyM0Btb25nby1zdmMvY29uZHVpdA==
kind: Secret
metadata:
  name: mongo-connection-string
---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: tarekesmail/nodejs-test-app
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: MONGODB_URI
          imagePullPolicy: Always
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp-service
spec:
  selector:
    app: nodejs-app 
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
---
#Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: nodejstestapp.com
spec:
  rules:
  - host: nodejstestapp.com
    http:
      paths:
      - backend:
          service:
            name: nodejsapp-service
            port:
              number: 3000
        path: /?(.*)
        pathType: Prefix
---